# Real world constants
track_bed_width: 1435  # mm
rail_width: 67  # mm

## Label tool parameters
# Paths
dataset_path: .
# Calculations
marker_interpolation_steps: 15  # steps
# Tags for scenes (only append)
tags:
  - snow
  - rain/fog
  - dazzling/blinding
  - dark/dawn/night
  - curve
  - stright
# GUI colors

## Pipeline script config

