name: RailLabel
channels:
  - conda-forge
dependencies:
  - python=3.9
  - opencv
  - black
  - pyyaml
  - tabulate
  - pip:
      - splines
      - iteration-utilities
      - pre-commit
      - PySimpleGUI
